version: '3.9'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./rabbitmq.env
